# testing
# This workflow works good for sending message to the slack group, differently for each success and failure case..
name: Test 3 Workflow

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send message to sahilrajput03
        uses: appleboy/telegram-action@master
        with:
          to: '711263195'
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # args: The ${{ github.event_name }} event triggered this.

      - name: send message to group fullstackopen
        uses: appleboy/telegram-action@master
        with:
          to: '@fullstackcourse'
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered this.

      - name: send message to group work-d-pc
        uses: appleboy/telegram-action@master
        with:
          to: '1001158282997'
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # args: The ${{ github.event_name }} event triggered this.
