# testing
# This workflow works good for sending message to the slack group, differently for each success and failure case.
name: Test Workflow 2

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Just something.
        run: |
          echo coool!
          # To mimic a failure case, just use some badCommand here, yikes!

      - name: Slack - Build success notification action.
        uses: 8398a7/action-slack@v3
        if: ${{success()}}
        # if: ${{always()}} # DEBUGGING...
        # NOTE: ${{}} is very important for success() and failure() command to behave properly, #tested!
        # Docs for action-slack: https://github.com/marketplace/actions/action-slack .
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `A new version of ${process.env.AS_REPO} deployed to https://pokedex-app-ex99.herokuapp.com/health (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} and build  took ${process.env.AS_TOOK}.`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      - name: Slack - Build failure notification action.
        if: ${{failure()}}
        # if: ${{always()}} # DEBUGGING...
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
